### ISSUE TITLE
KeyError 'request'

### ISSUE THREAD

**Issue by qcaron** [TyMaszWeb/django-cookie-law#9]
Hey guys,

When in the **admin**, I keep getting *KeyError 'request'* errors:

```
File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/cookielaw/templatetags/cookielaw_tags.py", line 18, in render_tag
   if context['request'].COOKIES.get('cookielaw_accepted', False)
```

Here is my whole traceback:
```
Internal Server Error: /favicon.ico
Traceback (most recent call last):
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 150, in get_response
   response = callback(request, **param_dict)
 File "./pickmystartup/views.py", line 1324, in page_not_found
   return HttpResponseNotFound(render_to_string('404.html'))
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
   return t.render(Context(dictionary))
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
   return self._render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
   return self.nodelist.render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
   bit = self.render_node(node, context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
   return node.render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
   return compiled_parent._render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
   return self.nodelist.render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
   bit = self.render_node(node, context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
   return node.render(context)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
   return self.render_tag(context, **kwargs)
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/cookielaw/templatetags/cookielaw_tags.py", line 18, in render_tag
   if context['request'].COOKIES.get('cookielaw_accepted', False):
 File "/srv/data/web/vhosts/default/local/local/lib/python2.7/site-packages/django/template/context.py", line 70, in __getitem__
   raise KeyError(key)
KeyError: 'request'
```

Is this related to the use of django-cookie-law or not? Any solution or thought?

**Comment by paolodina** [comment]
Hi, probably `django.template.context_processors.request` is not in `TEMPLATE_CONTEXT_PROCESSORS`.

**Comment by qcaron** [comment]
Indeed! I will give it a try, thanks :)

**Comment by qcaron** [comment]
```
ImportError at /
No module named context_processors
```
Am I missing something?

**Comment by qcaron** [comment]
And I am using `'django.core.context_processors.request'`.

**Comment by qcaron** [comment]
Ok I have a little bit more information on this error: for example, I the error is raised when using AJAX with `JsonResponse` in views. How may I avoid this error ??? This is important guys I really need help on this one =/

**Comment by qcaron** [comment]
Should we test for key ``request`` first ?
```python
if context.get('request') and context['request'].COOKIES.get('cookielaw_accepted', False):
     return ''
```

**Comment by centralniak** [comment]
Hi @qcaron,

Unfortunately django-cookie-law is not tested using Django 1.7 at the moment, so you'd have to work out way to handle this:
https://github.com/TyMaszWeb/django-cookie-law/blob/master/.travis.yml#L7

From your traceback it seems like you're using the `{% cookielaw_banner %}` tag in your `404.html` template (or the one `404.html` is extending).

There are a few issues here:

* you should rather not allow Django to serve your `favicon.ico`
* you should make your 404.html as simple as possible so you don't get further errors when for example the database dies
* `django-cookie-law` should rather raise a warning than an exception when request context is not found in the response.

It'd be great if you could take care of the last point and open a PR. Otherwise I'll try to look into this in the upcoming week.

**Comment by centralniak** [comment]
Hi @qcaron 

Can you please confirm that with version 1.0.6 this is fixed?

Thanks

**Comment by paolodina** [comment]
Shouldn't this https://github.com/TyMaszWeb/django-cookie-law/blob/master/cookielaw/templatetags/cookielaw_tags.py#L25 use `elif` instead of `if`?

**Comment by qcaron** [comment]
@centralniak I should be able to do some tests tomorrow ;)
But @paolodina is right, an error may be raised without using an `elif` here.

**Comment by qcaron** [comment]
@centralniak I confirm you that I still get the error.

**Comment by qcaron** [comment]
The `elif` is missing. Except that it should be good :)
